### ISSUE TITLE
Consider renaming the 'runtime' interface to 'store' for consistency with other WASI proposals

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/wasi-runtime-config#13]
Since originally suggesting `runtime` as the interface name, some naming conventions have emerged elsewhere in WASI, in particular, having the interface names be nouns instead of adjectives.  Also, wasi-keyvalue has `wasi:keyvalue/store` and there's a nice symmetry between that and `wasi:config/store`.

The original idea of `runtime` was to distinguish the runtime `get` lookup from a more declarative interface that allowed a component to statically enumerate the specific configuration values it needed as [value imports](https://github.com/WebAssembly/component-model/blob/main/design/mvp/Explainer.md#-value-definitions).  However, I think a "store" communicates this just as well and there are plenty of names left for declarative value imports.

**Comment by thomastaylor312** [comment]
This shouldn't be too hard to do. I do know that at least in wasmCloud we have a bunch of things that use this interface as it is currently, so we might have to do an adapter for this to ease the transition. But I also know we were thinking of cutting the actual 0.2.0 of this soon so probably good to do it now

**Comment by Mossaka** [comment]
agreed to the rename and agreed that this should be done prior to 0.2.0 cut
